import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for ROS 2 module
  tutorialSidebar: [
    {
      type: 'category',
      label: 'ROS 2 Robotics Module',
      items: [
        'intro',
        'modules/ros2-module/quickstart',
        {
          type: 'category',
          label: 'Chapter 1: ROS 2 Fundamentals',
          items: [
            'modules/ros2-module/chapter1-fundamentals',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 2: Robot Control Programming',
          items: [
            'modules/ros2-module/chapter2-control',
          ],
        },
        {
          type: 'category',
          label: 'Chapter 3: Robot Description and Modeling',
          items: [
            'modules/ros2-module/chapter3-urdf',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin (Gazebo & Unity)',
      items: [
        'module-2/gazebo-physics',
        'module-2/unity-environments',
        'module-2/simulated-sensors',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3/isaac-sim',
        'module-3/isaac-ros',
        'module-3/nav2-navigation',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4/voice-to-action',
        'module-4/cognitive-planning',
        'module-4/autonomous-humanoid',
      ],
    },
  ],
};

export default sidebars;
